# Generated by Django 4.2.25 on 2025-10-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publishing_date',
            field=models.DateTimeField(blank=True, help_text='When the article is published. Null means draft.', null=True),
        ),
    ]
